### ISSUE TITLE
Player prototype may break when player disconnects

### ISSUE THREAD

**Issue by xxshady** [xxshady/altv-esbuild#1]

**Comment by xxshady** [comment]
And I think it's related to this https://github.com/altmp/altv-js-module/issues/106

**Comment by ApollonSeven** [comment]
I have same error
```ts
import * as alt from 'alt-client';

export class TrafficCamera extends alt.LocalObject {
  public serverId: string | number;

  constructor(serverId: string | number, pos: alt.Vector3, rot: alt.Vector3) {
    super('ch_prop_ch_camera_01', pos, rot);
    this.frozen = true;
    this.serverId = serverId;

    this.text();
  }

  public text(){
    console.log(123);
  }
 }
```

Log error:
```
Uncaught exception in event listener of event "worldObjectStreamIn":
 TypeError: this.text is not a function
    at new TrafficCamera (client/index.js:4551:10)
    at TrafficCameraService.add (client/index.js:4570:5)
    at client/index.js:4530:35
    at f (client/index.js:28:2712) 
[V8] Exception at core:client/index.js:28 
${a}  `)} ${r[1]}`}it=function(e,n=!0){let r=0;n&&(e=ho(e)),e=Vn(e,"NFC");for(le... 
TypeError: this.text is not a function
    at new TrafficCamera (client/index.js:4551:10)
    at TrafficCameraService.add (client/index.js:4570:5)
    at client/index.js:4530:35
    at f (client/index.js:28:2712) 
TypeError: this.text is not a function 
```

**Comment by xxshady** [comment]
@ApollonSeven do you use js module v2 (btw your issue is unrelated to this one)

**Comment by ApollonSeven** [comment]
> @ApollonSeven do you use js module v2?

How can I check this? I have just `'js-module'` string in my server.toml

**Comment by xxshady** [comment]
then its v1
